// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD9XT_vEryIZJJvL5XZMBnmy2xGQoFfmk',
    appId: '1:117438888485:web:a0481a3b45e8e34fc09dcc',
    messagingSenderId: '117438888485',
    projectId: 'note-app-532f0',
    authDomain: 'note-app-532f0.firebaseapp.com',
    storageBucket: 'note-app-532f0.firebasestorage.app',
    measurementId: 'G-67T2ZJL1ZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFnS4LYHJmg_mYSB7oW6sA1_biXlB-1lI',
    appId: '1:117438888485:android:3e71c608caf5ea10c09dcc',
    messagingSenderId: '117438888485',
    projectId: 'note-app-532f0',
    storageBucket: 'note-app-532f0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQynCkVyB4d5CHSX6SQWR1Ar6r5eEUScU',
    appId: '1:117438888485:ios:ae25476985de1bdec09dcc',
    messagingSenderId: '117438888485',
    projectId: 'note-app-532f0',
    storageBucket: 'note-app-532f0.firebasestorage.app',
    iosBundleId: 'com.yourname.notes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQynCkVyB4d5CHSX6SQWR1Ar6r5eEUScU',
    appId: '1:117438888485:ios:ae25476985de1bdec09dcc',
    messagingSenderId: '117438888485',
    projectId: 'note-app-532f0',
    storageBucket: 'note-app-532f0.firebasestorage.app',
    iosBundleId: 'com.yourname.notes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBD9XT_vEryIZJJvL5XZMBnmy2xGQoFfmk',
    appId: '1:117438888485:web:d332e5ea381d183dc09dcc',
    messagingSenderId: '117438888485',
    projectId: 'note-app-532f0',
    authDomain: 'note-app-532f0.firebaseapp.com',
    storageBucket: 'note-app-532f0.firebasestorage.app',
    measurementId: 'G-CMV5S6HSFM',
  );
}
